version: "3.8"

# Services
services:
  # CEE Device Connector
  iaq_adapter_cee:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - gin_mode=release
        - mqtt_uri=mqtt://pi:woofaa@172.17.0.1:1883
        - mqtt_topics=GASDATA;GASDATA/#;UVSTATUS/CURRENTLIFETIME/#;UVSTATUS/SENDVALUE/#
        - rest_uri=http://172.17.0.1/api
        #- cloud_uri=https://demo.woofaa.com/api
    container_name: iaq_adpter_cee
    working_dir: /app
    #    depends_on:
    #      - mqtt
    restart: unless-stopped
